### ISSUE TITLE
Project # Items Needed For Next Level in Tooltip

### ISSUE THREAD

**Issue by Marstead** [TheStonedTurtle/banked-experience#10]
For instance, if I am looking at Teak Planks in the Construction section, I'd like the tooltip to tell me how many additional Teak Planks I'd need in order to hit the next level (Target Level +1).

**Comment by TheStonedTurtle** [comment]
I've added a label that displays how much experience is required for the next level (Target Level +1) in commit 36a4a8ae8e854af181bfbd1db1f5b5abe321bbb1. While this does not directly address your request I believe this is good enough as you can divide this value by the experience per action of whatever activity you'd like. In my opinion the feature you requested is too complicated to explain effectively inside the tooltip.

I am going to close this issue for now.
