### ISSUE TITLE
Prayer - Zealot Robes adding bonus XP to Ectofuntus when it should not

### ISSUE THREAD

**Issue by Yorkshire3322** [TheStonedTurtle/banked-experience#104]
As per the Wikipedia page for Zealot's Robes, the robes effects _do not_ provide benefit at the Ectofuntus.
![image](https://user-images.githubusercontent.com/9698240/220434765-7cea03dd-d017-4569-b7ce-7a47fd4043d1.png)

Here is an example:
No Zealot's Robe Pieces
![image](https://user-images.githubusercontent.com/9698240/220435015-ea20c234-be25-492d-88a2-0a18af0df96b.png)

4/4 Zealot's Robe Pieces
![image](https://user-images.githubusercontent.com/9698240/220435114-0ad02674-ccf2-47bf-b408-4605d3d7a3d1.png)

It shows that Dragon bones give an additional 15.16 xp/bone. This should not be taken into account with the bones when the Ectofuntus option is toggled on.

**Comment by SeaifanAladdin** [comment]
It has been [updated](https://oldschool.runescape.wiki/w/Update:More_Poll_79_Changes) in June that Zealot Robes will provide benefits at Ectofuntus

**Comment by TheStonedTurtle** [comment]
Closing as Jagex fixed this issue for me. Yay.
