### ISSUE TITLE
Crafting - Missing sand as required secondary for Molten Glass

### ISSUE THREAD

**Issue by daryl-daryl** [TheStonedTurtle/banked-experience#109]
Currently only counting (Giant)Seaweed/Soda Ash as an ingredient for glass, doesn't require or check Buckets of Sand

**Comment by TheStonedTurtle** [comment]
Per the README:
> Q: How can I limit experience based on the secondaries I have banked?
This is not currently possible. Some secondaries, like coal, are split between multiple activities which would require a prioritization system that I'm not sure how to implement.

I had to decide what is the "main" item for activities, in this case it was the Seaweed/Soda Ash.

You can see how many it would take, along with how many you have banked and/or are missing via the `Show required secondaries` config option.
![image](https://user-images.githubusercontent.com/29030969/233542870-3ba9f1db-6ffd-467b-b9e1-3bd6300d0160.png)
