### ISSUE TITLE
Zealot robe xp bonus is not properly calculated at wilderness chaos altar

### ISSUE THREAD

**Issue by uhhuhhoney** [TheStonedTurtle/banked-experience#110]
[Mod ash just confirmed the way the outfit works for the wilderness altar.](https://twitter.com/JagexAsh/status/1649324323402833920?s=20) This would result in a 52.5% chance to save a bone at the wilderness. This makes a dragon bone at the wildy altar while wearing zealots equal to 538.95 xp on average. In the plugin It's currently showing it as 530.53 for a dragon bone. So something is being calculated wrong there with the math. I would really appreciate if you could fix this :)

**Comment by TheStonedTurtle** [comment]
How are you coming up with this 538.95 value?

The math the plugin is doing is `base xp / consumptionChance`

Consumption chance in this case would be `1 - .525` which is `.475`.

Dbones are worth `72` xp, wildy altar gives `350%` xp so `72 * 3.5` = `252`

`252 / .475` = `~350.53`

**Comment by uhhuhhoney** [comment]
You're actually right, my bad. I was using 256 for my base xp on the dragon bone. Sorry to waste your time! No changes are needed on the plugin then, it works fantastically.
