### ISSUE TITLE
Add secondaries to prayer for reanimation spell

### ISSUE THREAD

**Issue by Windexatron** [TheStonedTurtle/banked-experience#112]
I loved the addition of adding runes needed for plank make, it would be great to have the same thing for reanimation spells in banked prayer. Great plugin even without it thanks for all the work!

**Comment by TheStonedTurtle** [comment]
PR #115 has been merged, hopefully I can get a release out to the hub within the next couple days. Unfortunately I'm pretty busy IRL and haven't had much time for RL related tasks.
