### ISSUE TITLE
Enhancement: Add Herb Seeds to Banked Herblore XP

### ISSUE THREAD

**Issue by usa-usa-usa-usa** [TheStonedTurtle/banked-experience#116]
It would be nice to be able to include my herb seed collection in my banked herblore XP.

According to the Wiki, [the average yield is 8.56 herbs per patch](https://oldschool.runescape.wiki/w/Herb_patch#cite_note-3).

**Comment by TheStonedTurtle** [comment]
Duplicate of #19 , tangentially related to #113
