### ISSUE TITLE
Extended Super Antifires not counted

### ISSUE THREAD

**Issue by jevonsp** [TheStonedTurtle/banked-experience#117]
Extended Super Antifires and its variants aren't counted, it would be great if antifire pots could calc number of secondaries needed and amount of exp that would be gained.

**Comment by TheStonedTurtle** [comment]
The method for creating extended super antifires with lava scales & super antifire potions already exists,

I've added the method using crushed dragon bones on extended antifire potions in commit af9ff8bccd700f74568e3aaa503a1efa8a208656

The new method only look for 4 dose potions.
