### ISSUE TITLE
Crafting - molten glass

### ISSUE THREAD

**Issue by Seanstable** [TheStonedTurtle/banked-experience#118]
Molten glass is showing up as if I had 600 in my bank but I have 0. Found out that my soda ash and seaweed equals out to what the plugin shows. Looks like it's counting seaweed and soda ash as molten glass even when you have 0 buckets of sand.

**Comment by TheStonedTurtle** [comment]
Buckets of Glass is considered a secondary and the plugin does not limit based on secondaries.
