### ISSUE TITLE
Feat: Exclude XP from missing secondaries

### ISSUE THREAD

**Issue by GregTheGreek** [TheStonedTurtle/banked-experience#124]
Happy to submit a PR if it's helpful.

### Feature
A toggle option that allow users to separate `Total Banked` number amount into two new values: banked with secondaries, and banked without secondaries.

**Banked without secondaries**
Displays the total amount of experience you would receive based on the total number of secondaries you have banked. 
**Banked with secondaries**
Operates the exact same way `Total Banked` works today in the interface

**Comment by TheStonedTurtle** [comment]
Similar to #9 I'd recommend you read that to see why I haven't attempted it but if you can create a PR for it sure.

**Comment by GregTheGreek** [comment]
Closing in favour of #9 Thanks for the reply
