### ISSUE TITLE
Suggestion: Add Guam-Marr vials as Guam and Marrentil Herblore training options

### ISSUE THREAD

**Issue by PenguinMeat** [TheStonedTurtle/banked-experience#126]
[Guam-Marr vials](https://oldschool.runescape.wiki/w/Guam-marr_vial) are a somewhat lesser known training method for Herblore where you use Guams and/or Marrentills on a vial during the Lunar Diplomacy quest. Its extremely efficient, especially for ironman accounts and grants more XP per herb than any other use for those herbs (84xp each herb).

The only downside with this method is that it becomes unavailable after you progress past the vial step in the quest.

**Comment by TheStonedTurtle** [comment]
Because access to this method is lost if you complete the quest and do not already have a vial I am not going to add it. Sorry :(
