### ISSUE TITLE
Arrowtips wrong xp value

### ISSUE THREAD

**Issue by ay-em** [TheStonedTurtle/banked-experience#138]
Current xp:
Steel arrowtips: 2.5xp per
Mithril arrowtips: 5xp per

Actual xp:
Steel arrowtips: 5xp per
Mithril arrowtips: 7.5xp per

**Comment by TheStonedTurtle** [comment]
Fixed in bb3004bc107c47cf19f5bb59ad0e3d4a16dcf3e0
