### ISSUE TITLE
Add support for gold bar processing without gems

### ISSUE THREAD

**Issue by SieBrum** [TheStonedTurtle/banked-experience#14]
Items:
- gold ring (1 bar, 15 exp)
- gold necklace (1 bar, 20 exp)
- gold bracelet (1 bar, 25 exp)
- gold amulet (u) (1 bar, 30 exp)
- (golden) helmet (3 bars, 30 exp, requires between a rock)
- Bowl (2 bars, 30 exp, requires legends quest)

Most of these items are useless and pretty dead crafting content. [But crafting gold bracelets is used quite often for both mains and ironmen (see wiki, other methods; gold bracelets)](https://oldschool.runescape.wiki/w/Pay-to-play_Crafting_training) because its a commonly alched item.

**Comment by TheStonedTurtle** [comment]
I'm going to add this but not the Golden helmet or bowl. The helmet is worse exp so no reason to do it and the Bowl is the same exp as the gold ring option.

**Comment by SieBrum** [comment]
Understandable, was just getting all the gold bar possibilities in one small list for ya.

**Comment by bardonl** [comment]
Thanks a lot! Do you have any indication on when a PR will be made to the RL plugin hub? :)
