### ISSUE TITLE
Prayer: The Demonic Offering (300% xp) option doesn't do anything

### ISSUE THREAD

**Issue by scrapmuffin** [TheStonedTurtle/banked-experience#140]
https://i.imgur.com/cAbE20O.png toggled off
https://i.imgur.com/Utkpxys.png Toggled on
same amount of xp given

**Comment by SeaifanAladdin** [comment]
Your screenshot doesn't show your resources. Demonic Offering only applies to ashes. Do you have any ashes as a resource? Potential duplicate #134.

To prevent future confusion, maybe we can add a tooltip to clarify it's applicable to only ashes, or add Sinister Offering as an option (which applies to bones)?
