### ISSUE TITLE
Visit Bank Message

### ISSUE THREAD

**Issue by njw4227** [TheStonedTurtle/banked-experience#15]
I am on version 1.4 of the plugin and I keep getting this message and not sure how to fix it. (Yes I am in my bank when I get this message)
![bankedxp](https://user-images.githubusercontent.com/47066666/77581110-8357eb80-6eb3-11ea-9883-c0265bd0dc28.PNG)

**Comment by TheStonedTurtle** [comment]
Once you visit a bank you need to change categories, the ui doesnt auto
update when the bank content changes.

**Comment by TheStonedTurtle** [comment]
I'm assuming you figured this out and am closing this issue.
