### ISSUE TITLE
Ancient Essence herblore calculation is incorrect

### ISSUE THREAD

**Issue by hollyroberts** [TheStonedTurtle/banked-experience#154]
I recently noticed that I had 10m banked herblore XP all of a sudden. This appears to be due to the ancient essence in my bank [screenshot](https://github.com/user-attachments/assets/bc650fd1-4ec9-4b64-8a88-7c58bdeb9db9) which gives 36xp/action. The [wiki page](https://oldschool.runescape.wiki/w/Forgotten_brew#Creation) for making forgotten brews says that each dose requires 20 essence, so the xp/action should be 1.8. I believe this issue was introduced [here](https://github.com/TheStonedTurtle/banked-experience/commit/84451b8cb44ff2da332bbe489ca05699c7a690f9#diff-d1ff97928560709717c122d22713d94f7a123b8d9c3b295bd7a90777a3f5b016R281).  

Unrelated to the calculation here, as a user I find this choice of primary/secondary to be the wrong way around. I can obtain thousands of essence from Muspah with ease, but ancient brews are difficult and slow. I also passively obtain essence going for venator bow/ancient icon, whereas ancient brews are more of an issue. Nex is done later than Muspah, and even with Nihil dust you need unfinished dwarf weed potions which is a primary for making ancient brews.

**Comment by TheStonedTurtle** [comment]
Fixed in c0373c43a3ffd60cccfde22343bc00575ce9584f
