### ISSUE TITLE
Enhancement Herblore - stamina potions counting from Avantoe herbs

### ISSUE THREAD

**Issue by splash675** [TheStonedTurtle/banked-experience#156]
The output from Avantoes show super energies but doesn't show super energy to stamina pot.

![image](https://github.com/user-attachments/assets/d3e3b94b-84bd-4f7a-9587-f908903590dc)

Creating a stamina pot (3) from a super energy (3) gives 76.5xp. Having the option to include stamina pots from avantoe will enhance the plugin as Irons have this pipeline: Avantoe > Super energy > Stamina. Altogether this would result in 117.5xp (super energy) + 76.5xp (stamina) = 194xp

Showing the number of secondaries required for (3) doses would be 1 Mort myre fungus + 3 Amylase Crystal for every 1 Avantoe herb

**Comment by TheStonedTurtle** [comment]
Stamina potions are based off of Marks of Grace/Amalayse crystals, this was done as those are the harder item to acquire for ironmen and thus are typically the limiting factor.

While I could add this as an option I would prefer not to have two different item sources (experience items) for the same activity as it may double-count your experience if you setup both of them for the same activity.
