### ISSUE TITLE
(suggestion) Banked Farming Experience - Pull from Seed Vault 

### ISSUE THREAD

**Issue by ehhhhhok** [TheStonedTurtle/banked-experience#18]
Whenever trying to use the banked experience plugin, it only pulls from the seeds and saplings in my bank. I don't think many people keep these items in their banks, but rather the seed vault.

I would suggest having the banked farming experience have the option to pull from the seeds and saplings from your bank, the seed vault, or both.

**Comment by TheStonedTurtle** [comment]
There is already a config option to accomplish this.

![image](https://user-images.githubusercontent.com/29030969/79525284-56f94000-8017-11ea-83e6-285a44aa5d07.png)

**Comment by ehhhhhok** [comment]
There may already be a config for it, but it doesn't work. I have around 50m in seeds banked, but its only showing the 21k experience from the seeds in my bank.

**Comment by TheStonedTurtle** [comment]
> there may already be a config for it, but it doesn't work. I have around 50m in seeds banked, but its only showing the 21k experience from the seeds in my bank.

The plugin only includes items with a fixed experience rate, so things like herbs are excluded because the amount of herbs received varies dramatically. If there are specific item that are missing that you think should be included feel free to create a new issue listing them.
