### ISSUE TITLE
See banked XP in planks without including logs

### ISSUE THREAD

**Issue by hjdarnel** [TheStonedTurtle/banked-experience#2]
Hey, thanks for putting together this plugin!

One use case that I came across immediately is that I wanted to see how much xp my banked teak planks were worth, without including the output of the banked teak logs. I went into the settings and disabled "Include output items", which got me the option to select the teak planks that I have without including the logs-to-be-made into planks. It would be cool if this was on the main of the UI so that I could toggle it easily.

Thanks for your work!
Sick Hangs from overflow

**Comment by TheStonedTurtle** [comment]
Hey sick hangs,

You should be able to right-click items inside the grid and ignore them,
this will remove it from the xp calculation and from cascading its output.
You can right-click to include the ignored item as well

**Comment by TheStonedTurtle** [comment]
![https://i.imgur.com/WoQyU45.png](https://i.imgur.com/WoQyU45.png)

**Comment by TheStonedTurtle** [comment]
I'm closing this issue, feel free to re-open if the above didn't solve your issue.

**Comment by hjdarnel** [comment]
Yeah, that works alright for me! Thanks :)
