### ISSUE TITLE
[Feature request] Add UIM/looting bag support

### ISSUE THREAD

**Issue by JonathanOuwens** [TheStonedTurtle/banked-experience#20]
Hi,

Me and a clanmate would like to be able to see how much experience we have in our looting bags on our UIMs. Is it doable to make it check for a looting bag in the inventory?

Jonathan

**Comment by TheStonedTurtle** [comment]
The option to include items inside your Inventory and Looting bag was adding in commit b227a2cc86a037c24269ea05b988f43c1b8ff7e4 and will be available once the next release has been merged (v1.6). These options default to off, so make sure to check the config option. You must check the Looting bag for the plugin to register it, and if you are already viewing a skill you must select a new one for the UI to update.
