### ISSUE TITLE
UIM support

### ISSUE THREAD

**Issue by JonathanOuwens** [TheStonedTurtle/banked-experience#22]
Hiya!

First of all, thanks for implementing UIM support! Seriously appreciate it. :)

However, it doesn't work for UIM yet. I still need to open a bank to be able to use the plugin. Could this be fixed? Not sure if removing the requirement to open the bank would break the plugin, but if so, maybe add an or to open the looting bag.

Thanks a lot!

Kind regards,

Jonathan

**Comment by TheStonedTurtle** [comment]
Hey Jonathan, did you happen to select the skill in the drop-down prior to checking your looting bag and do you 0have the config options enabled for these features? (they default to off)

The UI does not automatically update when the Bank (or in this case Inventory or Looting bag) contents has changed as it might cause performance issues. You must select a different skill then your previous one to refresh the UI. I've updated the README recently to explain a bit more about the plugin.

NOTE: The plugin requires you to manually check the looting bag, but it should register your inventory upon login. The plugin can not register when the looting bag contents have changed, it must be re-checked. For example if you pick up items while its open or use items on the looting bag the plugin won't know that the looting bag now contains those items.

I can't replicate the issue so I'm going to close it.
