### ISSUE TITLE
Ultimate Ironman compatibility

### ISSUE THREAD

**Issue by RenewedRS** [TheStonedTurtle/banked-experience#24]
I noticed a looting bag addition was added to it recently, and I have to presume that was a suggestion from a UIM, but it still requires you to open a bank to actually update the calc.
Bagged xp is a huge thing for Ultimate Ironmen so this kind of calculator would be amazing for the mode.
Is there a chance it could calculate inventory + looting bag for UIMs?

**Comment by TheStonedTurtle** [comment]
Hello, do you have the config option for the looting bag enabled? You must manually check the looting bag (using the right-click option on the bag) before selecting the skill. If you select the skill before checking it will show the `Please visit a bank` message.

> The UI does not automatically update when your bank content changes, you must change skills for the updates to be applied. This was done intentionally to minimize performance issues from constantly refreshing the UI

So if you selected a skill, saw the visit bank message, and then checked your looting bag you need to change to a different skill then back. 


I just tested this and it seems to be working as expected for me.
