### ISSUE TITLE
UI dosent update

### ISSUE THREAD

**Issue by HumbleNoodle** [TheStonedTurtle/banked-experience#25]
it says visit a bank when i am in the bank window, i have tested starting the pluging when im in the bank an vice versa and still the same

**Comment by TheStonedTurtle** [comment]
You may need to restart your client, There was an issue with this plugin when RuneLite updated after the Jagex update that caused the plugin to silently break. If you go to the plugin-hub and look at the plugin it should show a version, if you see `1.6.1` and are still having this issue let me know.
