### ISSUE TITLE
Lava scale shard xp

### ISSUE THREAD

**Issue by Deery11** [TheStonedTurtle/banked-experience#29]
The exp for lava scale shards used in Extended super antifires is 40xp per dose, the banked xp tracker indicates it is the same as normal Extended antifires (25.5xp per dose)

https://oldschool.runescape.wiki/w/Extended_super_antifire#4_dose

![Lava Scale Shard](https://user-images.githubusercontent.com/73571129/97388048-44ed3980-18a5-11eb-87f5-f2d7fbba6b5b.PNG)

**Comment by TheStonedTurtle** [comment]
That has been fixed in v1.6.3
