### ISSUE TITLE
Support for trailblazer league xp rates

### ISSUE THREAD

**Issue by pelletier2017** [TheStonedTurtle/banked-experience#30]
When in a trailblazer world, the plugin could calculate banked experience based on their relics and xp multipliers. The xp multipler should be pretty easy, just multiply result xp based on how many relics they have unlocked. Equilibrium might be more difficult because its a flat bonus based on total level but in general its 1 tick of bonus xp per tick of experience.

**Comment by TheStonedTurtle** [comment]
Little late for a response as the league has ended, but I have been busy with school and have taken a break from RS so I did not play leagues.
