### ISSUE TITLE
Feature Request: Include Superglassmake option for Giant seaweed

### ISSUE THREAD

**Issue by Regelios** [TheStonedTurtle/banked-experience#31]
On average one Giant seaweed is equal to 9.6 molten glass if you are using the spell with 3 in your inventory and picking up the excess. Could this be added as an option as an addition to the soda ash conversion that is there currently? The sources for the numbers I am using is from the wiki page on Giant seaweed.

"The average Crafting experience per giant seaweed varies:

For an average of 1.45 glass per sand (two giant seaweed and 12 buckets of sand), each giant seaweed equals 538.5 experience when making lantern lenses or 669 experience when making empty light orbs;
For an average of 1.488 glass per sand (three giant seaweed and 18 buckets of sand without picking up the excess), each giant seaweed equals 551 experience when making lantern lenses or 685 experience when making empty light orbs;
For an average of 1.6 glass per sand (three giant seaweed and 18 buckets of sand and picking up the excess), each giant seaweed equals 588 experience when making lantern lenses or 732 experience when making empty light orbs.
These numbers include the experience from casting Superglass Make." ("Giant seaweed," "Uses," para. 3)

**Comment by TheStonedTurtle** [comment]
Should already exist, just turn on `RNG Activities` in the config panel.

**Comment by Regelios** [comment]
Sorry about that, it seems your plugin was more advanced than I realized. Thank you for work by the way it saves a lot of headaches.
