### ISSUE TITLE
Prayer banked xp bug

### ISSUE THREAD

**Issue by elkcarc** [TheStonedTurtle/banked-experience#46]
Banked xp for prayer currently appears to have the gilded altar modifier affect ensouled heads, so when the gilded altar box is checked it multiples ensouled head xp in addition to bones. This results in dramatically overinflated banked xp when the gilded altar box is selected.

![image](https://user-images.githubusercontent.com/42009371/116192467-e55cd300-a6fb-11eb-99da-2161234c0658.png)

![image](https://user-images.githubusercontent.com/42009371/116192482-e988f080-a6fb-11eb-9ca1-e6783855e113.png)

**Comment by TheStonedTurtle** [comment]
This has been fixed in commit 4cc2191650c7fae28be05d27f08d012fdd67204a
