### ISSUE TITLE
Feature Request - Not adding in some xp

### ISSUE THREAD

**Issue by Dustin1100** [TheStonedTurtle/banked-experience#60]
If the target level that is achievable through currently unlocked and available items is greater than or equal to the required level for some items that are not unlocked at the current level, it would make sense to add the not currently unlocked experience too. With the note that it will be available at 'required level'.

**Comment by TheStonedTurtle** [comment]
While not ideal this can now be achieved through the `Temporary Boost` option inside the plugin. You will still need to manually set this value. 

![image](https://github.com/TheStonedTurtle/banked-experience/assets/29030969/80685c46-3ed5-4de1-9489-9731fe2c9b59)
