### ISSUE TITLE
Feature request - Add boosts for level requirements

### ISSUE THREAD

**Issue by Freeburn113** [TheStonedTurtle/banked-experience#67]
Would there be a possibility to add boosts into the calculations as a tickbox? for example: Garden pie +3 farming, Cider +1 farming, Botanical pie +4 herblore

**Comment by TheStonedTurtle** [comment]
There is now a spinner input that you can enter a number between 0 and 99 to accomplish this manually. It is only shown when the `Respect Level Requirement` config option is disabled.

Added in 93bb715ad20ba32fbd61decea7741cf0f1821161
