### ISSUE TITLE
Idea - Add option to ignore level rqmt for banked calculation

### ISSUE THREAD

**Issue by PJGJ210** [TheStonedTurtle/banked-experience#87]
Config option to ignore level requirements when determining action (or temp boost checkmark that essentially sets you at 99).

Purpose of this would be to be able to not ignore specific mats as they will be used later while allowing one to see potential total banked experience. 

Else a more involved update would be to be able to set what mat will be used for regardless of level and only show xp to level/level achieved as this but show total banked ignoring level (if this makes sense). 

Ex.
Currently 80 herblore and unable to determine total banked experience assuming I will use toadflax on sara brews not agility potions. I can set boost to 81 but will have to do this every time. Else I have to keep toadflax ignored.

Ex2.
For construction I could not set my mahogany/teak logs to just be at mahogany homes and as such ignored this. I can manually set to +99 levels but again not perm solution to set and forget.

**Comment by TheStonedTurtle** [comment]
![image](https://user-images.githubusercontent.com/29030969/187091692-aef3b43e-2420-4095-bef7-4a93aba87013.png)
There's already a config option for this.
