### ISSUE TITLE
Feature Request: Add Brews to toadflax potions.

### ISSUE THREAD

**Issue by aftrosrs** [TheStonedTurtle/banked-experience#88]
having toadflax potions only option as agility pot kinda throws off what you have banked bc nobody makes agility pots with toadflax, unless they really dont have 72 herb

**Comment by TheStonedTurtle** [comment]
They are already added.
![image](https://user-images.githubusercontent.com/29030969/188747167-d8fbad7b-9c1f-40e0-bf8e-885dfb25ae5f.png)

You must not have 81 herblore to make them and have the `Respect level requirements` config option enabled
