### ISSUE TITLE
Feature request - Include bird nests as a banked secondary for brews

### ISSUE THREAD

**Issue by MathijsHaakman** [TheStonedTurtle/banked-experience#93]
I don't know how feasible this is, but it would be nice if the banked secondaries would show banked bird nests as well as banked crushed nests.

**Comment by TheStonedTurtle** [comment]
Non crushed birds nests (that have been emptied) will now be included in the total when looking at crushed nests

Added in commit e1bff4cd7de2a41672ffca28bf55a9cf2a0af2ad
